### ISSUE TITLE
pip install support

### ISSUE THREAD

**Issue by angerhang** [EPFL-LCN/neuronaldynamics-exercises#13]
After the recent update, pip is no longer supported and pip install directly from Github fails with `req` not found. Do you think we can add pip support back instead of requiring everyone to use miniconda :D

**Comment by angerhang** [comment]
It turns out that `pip -V` 10.0.0b2 is not compatible with the current `setup.py` which throws an error:
```python
(my-env) (bmnn) tsf-444-wpa-2-033:bioNN_EPFL_2018 Hang$ pip install -e git+https://github.com/EPFL-LCN/neuronaldynamics-exercises.git
Could not detect requirement name for 'git+https://github.com/EPFL-LCN/neuronaldynamics-exercises.git', please specify one with #egg=your_package_name
(my-env) (bmnn) tsf-444-wpa-2-033:bioNN_EPFL_2018 Hang$ pip install git+https://github.com/EPFL-LCN/neuronaldynamics-exercises.git
Collecting git+https://github.com/EPFL-LCN/neuronaldynamics-exercises.git
  Cloning https://github.com/EPFL-LCN/neuronaldynamics-exercises.git to /private/var/folders/zv/8tdb08g97ql362y6_p5lk7280000gn/T/pip-req-build-x1j4sW
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/zv/8tdb08g97ql362y6_p5lk7280000gn/T/pip-req-build-x1j4sW/setup.py", line 2, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req
```

However, downgrading pip to 9.0.3 resolves this issue. The compatibility should be checked nonetheless.

**Comment by flinz** [comment]
@angerhang thanks for bringin this to our attention - I agree we should pick up pip/pypi support again, which was dropped in the last release.
@MarcoLehmann could you please have a look? The comment by @angerhang should provide hints as what to do. If you want I can also have a look.
